[package]
name = "facilitest-macros"
version = "1.0.0"
authors = ["Stefan Scheller <ste.scheller@gmail.com>"]
edition = "2021"
description = "internal dependency of 'facilitest' package"
license = "MIT"

[lib]
path = "lib.rs"
proc-macro = true